language: php

php:
  - 5.3
  - 5.4

script: phpunit -c tests/phpunit.xml

before_script:
  - pyrus install -f http://download.pear.php.net/package/PEAR-1.9.4.tgz
#  - pyrus install -f -p pyrus/Pyrus_Developer
#  - pyrus install -f pear2.php.net/PEAR2_Exception